import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { test } from 'node:test';

test('frontend keeps VAbs splash copy and requested palette', async () => {
  const html = await readFile(new URL('../frontend/index.html', import.meta.url), 'utf8');
  const css = await readFile(new URL('../frontend/styles.css', import.meta.url), 'utf8');

  assert.match(html, /VAbs Solution/);
  assert.match(html, /Visual counting intelligence/);
  assert.match(html, /maximum-scale=1/);
  assert.match(html, /user-scalable=no/);
  assert.match(html, /viewport-fit=cover/);
  assert.match(css, /#221546/i);
  assert.match(css, /#6ef4f3/i);
  assert.match(css, /#ffffff/i);
  assert.match(css, /100dvh/);
  assert.match(css, /safe-area-inset-bottom/);
  assert.match(css, /touch-action:\s*pan-y/);
  assert.doesNotMatch(css, /#e9eef5|#f5f6f8|#fff3f3|#ef4444/i);
  assert.match(css, /\[hidden\]\s*\{\s*display:\s*none\s*!important;\s*\}/);
});

test('frontend mirrors BA app route shell with VAbs branding and camera counting flow', async () => {
  const app = await readFile(new URL('../frontend/app.js', import.meta.url), 'utf8');
  const css = await readFile(new URL('../frontend/styles.css', import.meta.url), 'utf8');
  const frontendServer = await readFile(new URL('../frontend/server.mjs', import.meta.url), 'utf8');

  assert.match(app, /function renderHome/);
  assert.match(app, /function lockMobileZoom/);
  assert.match(app, /gesturestart/);
  assert.match(app, /gesturechange/);
  assert.match(app, /touchend/);
  assert.match(app, /function filteredClasses/);
  assert.match(app, /function updateHomeResults/);
  assert.match(app, /function attachProductStartActions/);
  assert.match(app, /id="homeSearch"/);
  assert.match(app, /id="productList"/);
  assert.match(app, /VAbs Counting/);
  assert.match(app, /updateHomeResults\(\);/);
  assert.match(app, /function renderDrafts/);
  assert.match(app, /function renderSent/);
  assert.match(app, /function renderProfile/);
  assert.match(app, /function renderSkuConfirm/);
  assert.match(app, /function renderCamera/);
  assert.match(app, /function startLiveCamera/);
  assert.match(app, /function prefersNativeCameraCapture/);
  assert.match(app, /function startCaptureFlow/);
  assert.match(app, /function imageToJpegDataUrl/);
  assert.match(app, /function detectSelectedImage/);
  assert.match(app, /function friendlyCaptureError/);
  assert.match(app, /function captureLiveFrame/);
  assert.match(app, /navigator\.mediaDevices\?\.getUserMedia/);
  assert.match(app, /cameraInput\.click\(\)/);
  assert.match(app, /id="cameraVideo"/);
  assert.match(app, /id="captureCanvas"/);
  assert.match(app, /function renderVerify/);
  assert.match(app, /function verifyPhotoStyle/);
  assert.match(app, /style="aspect-ratio:\$\{width\} \/ \$\{height\}"/);
  assert.match(app, /<div class="verify-photo" \$\{verifyPhotoStyle\(\)\}>/);
  assert.match(app, /function renderReview/);
  assert.match(app, /\/home/);
  assert.match(app, /\/drafts/);
  assert.match(app, /\/draft/);
  assert.match(app, /\/sent/);
  assert.match(app, /\/profile/);
  assert.match(app, /\/camera\/sku/);
  assert.match(app, /\/camera/);
  assert.match(app, /\/verify/);
  assert.match(app, /\/review/);
  assert.match(app, /type="file"/);
  assert.match(app, /capture="environment"/);
  assert.match(app, /accept="image\/\*"/);
  assert.match(app, /await runDetect\(\)/);
  assert.match(app, /void setImageFromFile\(event\.currentTarget\.files\?\.\[0\], event\.currentTarget\)/);
  assert.match(app, /captureInput\.value = '';/);
  assert.match(app, /imageToJpegDataUrl\(image\)/);
  assert.match(app, /กำลังนับสต็อก/);
  assert.match(app, /targetClassId: selectedClass\.id/);
  assert.match(app, /VABS-\$\{String\(item\.id\)\.padStart\(3, '0'\)\}/);
  assert.match(app, /VAbs Vision/);
  assert.match(app, /function saveDraft\(\)[\s\S]*navigate\('\/home'\);/);
  assert.match(app, /function sendDrafts\(\)[\s\S]*navigate\('\/home'\);/);
  assert.match(app, /function saveDraft\(\)[\s\S]*searchTerm = '';/);
  assert.match(app, /function sendDrafts\(\)[\s\S]*searchTerm = '';/);
  assert.match(app, /drafts = \[currentDraftPayload\(\), \.\.\.drafts\];/);
  assert.doesNotMatch(app, /filter\(\(item\) => item\.sku !== classSku\(selectedClass\)\)/);
  assert.doesNotMatch(app, /selectedLocation|locationLabel|data-location|สต็อกหน้าร้าน|สต็อกหลังร้าน|สถานที่:/);
  assert.doesNotMatch(app, /YOLO|yolo/);
  assert.doesNotMatch(app, /homeSearch'[\s\S]{0,140}renderHome\(\)/);
  assert.doesNotMatch(app, /detectButton/);
  assert.doesNotMatch(app, /BarcodeDetector|scan barcode|สแกนบาร์โค้ด/);
  assert.doesNotMatch(app, /if \(!selectedImage && !cameraStream && liveCameraStatus === 'idle'\) startLiveCamera\(\);/);
  assert.match(css, /--app-width:\s*min\(100vw,\s*430px\)/);
  assert.match(css, /width:\s*var\(--app-width\)/);
  assert.match(css, /\.app-header/);
  assert.match(css, /\.bottom-nav/);
  assert.match(css, /\.counting-band/);
  assert.match(css, /\.product-confirm\s*\{[^}]*padding-bottom:\s*calc\(148px \+ var\(--safe-bottom\)\);/s);
  assert.match(css, /\.hero-product\s*\{[^}]*height:\s*clamp\(200px,\s*30dvh,\s*250px\);[^}]*position:\s*relative;/s);
  assert.match(css, /\.hero-product img\s*\{[^}]*position:\s*absolute;[^}]*inset:\s*8px;[^}]*width:\s*calc\(100% - 16px\);[^}]*height:\s*calc\(100% - 16px\);[^}]*object-fit:\s*contain;/s);
  assert.match(css, /\.camera-content,\s*\.review-content\s*\{[^}]*padding-bottom:\s*calc\(148px \+ var\(--safe-bottom\)\);/s);
  assert.match(css, /\.camera-stage\s*\{[^}]*height:\s*clamp\(280px,\s*46dvh,\s*430px\);/s);
  assert.match(css, /@media \(max-height:\s*780px\)/);
  assert.match(css, /@media \(max-height:\s*680px\)/);
  assert.doesNotMatch(css, /\.location-tabs/);
  assert.match(css, /\.verify-content\s*\{\s*padding-bottom:\s*calc\(168px \+ var\(--safe-bottom\)\);/);
  assert.match(css, /\.verify-photo\s*\{[^}]*aspect-ratio:\s*4 \/ 3;/s);
  assert.match(css, /#221546/i);
  assert.match(css, /#6ef4f3/i);
  assert.match(frontendServer, /!extname\(rawPath\)/);
});
